
import 'bookModel.dart';

var categoryData=[
  {
    "icon":"assets/icons/green.svg",
    "label":"Rommance",
  },
  {
    "icon":"assets/icons/flight.svg",
    "label":"Travel",
  },
  {
    "icon":"assets/icons/google.svg",
    "label":"Love Story",
  },
  {
    "icon":"assets/icons/search.svg",
    "label":"Documentry",
  }
];

var bookData = [
  BookModel(
    id: "1",
    title: "A Million To One",
    description: "A suspenseful tale of a daring heist aboard the Titanic, where a group of thieves come together to pull off the impossible.",
    aboutAuthor: "Toney is a bestselling author known for thrilling historical fiction with strong characters and immersive storytelling.",
    audioLen: "20",
    bookUrl: "assets/images/book2.jpg",
    rating: 4.2,
    category: "Documentary",
    price: 100,
    pages: 120,
    language: "English",
    author: "Yuvraj Singh",
    numberOfRating: 250,
  ),
  BookModel(
    id: "2",
    title: "The Journey",
    description: "An inspiring story about self-discovery, growth, and the road less traveled.",
    aboutAuthor: "Singh is a motivational speaker and author who writes deeply personal and uplifting stories.",
    audioLen: "20",
    bookUrl: "assets/images/book3.webp",
    rating: 4.2,
    category: "Travel",
    price: 100,
    pages: 130,
    language: "English",
    author: "King",
    numberOfRating: 310,
  ),
  BookModel(
    id: "3",
    title: "The Book Of Art",
    description: "A visual journey through time exploring the most iconic works of art across different cultures and eras.",
    aboutAuthor: "Hi Yuvraj Singh is an art historian and professor specializing in classical and modern art.",
    audioLen: "20",
    bookUrl: "assets/images/book4.jpg",
    rating: 4.2,
    category: "Documentary",
    price: 100,
    pages: 140,
    language: "English",
    author: "Walker",
    numberOfRating: 150,
  ),
  BookModel(
    id: "4",
    title: "Hide and Seek",
    description: "A gripping psychological thriller where nothing is as it seems and the past refuses to stay buried.",
    aboutAuthor: "Hi Yuvraj Singh is known for his masterful storytelling and ability to keep readers on the edge of their seats.",
    audioLen: "20",
    bookUrl: "assets/images/book5.webp",
    rating: 4.2,
    category: "Thriller",
    price: 100,
    pages: 110,
    language: "English",
    author: "Yuvraj Singh",
    numberOfRating: 100,
  ),
  BookModel(
    id: "5",
    title: "Alone",
    description: "A heartfelt narrative about solitude, resilience, and the beauty of finding strength within.",
    aboutAuthor: "Hi Yuvraj Singh is a contemporary fiction author who writes emotionally resonant stories about human connection.",
    audioLen: "20",
    bookUrl: "assets/images/book6.webp",
    rating: 4.2,
    category: "Romance",
    price: 100,
    pages: 110,
    language: "English",
    author: "Yuvraj Singh",
    numberOfRating: 100,
  ),
  BookModel(
    id: "6",
    title: "The Last Whisper",
    description: "In a world full of noise, one voice fights to be heard. A dramatic love story entangled in mystery.",
    aboutAuthor: "Hi Yuvraj Singh blends poetic prose with deep emotional insight, crafting unforgettable characters and settings.",
    audioLen: "20",
    bookUrl: "assets/images/book7.webp",
    rating: 4.2,
    category: "Love Story",
    price: 100,
    pages: 110,
    language: "English",
    author: "Yuvraj Singh",
    numberOfRating: 100,
  ),
];

